### ISSUE TITLE
node 11下运行报错

### ISSUE THREAD

**Issue by haovincent2016** [devin87/web-uploader-node#6]
fs.js:141
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function，
是不是跟node不兼容导致？怎么改呢

**Comment by haovincent2016** [comment]
是formidable\lib\下文件报的错

**Comment by devin87** [comment]
重新安装依赖试试，我这边安装 node v14.15.4 可以正常运行。
